name: Build wheel

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-wheel:
    strategy:
      matrix:
        python_tag: ["cp37", "cp38", "cp39", "cp310", "cp311"]
        os_and_platform_tag:
          - [ubuntu-latest, manylinux_x86_64]
          - [ubuntu-latest, manylinux_i686]
          # [ubuntu-latest,  manylinux_aarch64] # unsupported
          # [ubuntu-latest,  manylinux_ppc64le] # unsupported
          # [ubuntu-latest,  manylinux_s390x]   # unsupported
          # [macos-10.5,     macosx_*]          # deprecated
          - [macos-11, macosx_*]
          - [macos-12, macosx_*]
          - [windows-latest, win_amd64]
          - [windows-latest, win32]

    name: Build wheel for ${{ matrix.python_tag }}-${{ matrix.os_and_platform_tag[1] }}
    runs-on: ${{ matrix.os_and_platform_tag[0] }}
    continue-on-error: true
    env:
      IS_32BIT: ${{ matrix.os_and_platform_tag[1] == 'win32' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.7.1"
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Configure mingw for 32-bit builds
        if: ${{ env.IS_32_BIT == 'true' }}
        run: |
          choco uninstall mingw
          choco install -y mingw --forcex86 --force --version=7.3.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          refreshenv

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.10.2
        with:
          output-dir: dist
        env:
          CIBW_BUILD: ${{ matrix.python_tag }}-${{ matrix.os_and_platform_tag[1] }}

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.whl
          if-no-files-found: error
